version: '3'
services:

  altinn-model-publisher:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/altinn-model-publisher:test
    ports:
      - "8080:8080"
    environment:
      - ALTINN_URI=http://wiremock:8080
      - ALTINN_MODEL_PUBLISHER_URI=http://altinn-model-publisher:8080
      - ORGANIZATION_CATALOGUE_URI=https://organization-catalogue.fellesdatakatalog.digdir.no
    depends_on:
      - publishers-cache
      - wiremock

  publishers-cache:
    image: redis:latest
    ports:
      - 6379:6379

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8000:8080"
    volumes:
      - ./mock_mappings/mappings:/home/wiremock/mappings
