version: '3'
services:

  altinn-model-publisher:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/altinn-model-publisher:test
    ports:
      - "8080:8080"
    environment:
      - ALTINN_URI=http://wiremock:8080
      - ALTINN_MODEL_PUBLISHER_URI=http://altinn-model-publisher:8080
      - ORGANIZATION_CATALOGUE_URI=https://organization-catalogue.fellesdatakatalog.digdir.no
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
    depends_on:
      - mongodb
      - wiremock

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8000:8080"
    volumes:
      - ./mock_mappings/mappings:/home/wiremock/mappings
